services:
  postgres-db:
    image: postgres:15
    container_name: smartcv-postgres
    environment:
      POSTGRES_USER: smartcvuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartcvdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: